/*
 * GWT compliant generated by Fujaba - CodeGen2 version 25.3.2009
 */

package fast;

// GWT: fast.FactAttribute
// GWT: java.util.*

import java.util.*;
// GWT: de.upb.tools.fca.*

import fujaba.web.runtime.client.*;
// GWT: fast.ServiceDesigner
// GWT: de.upb.tools.sdm.*

// GWT: fast.FastObject
import fujaba.web.runtime.client.reflect.*;
import fujaba.web.runtime.client.*;
import java.util.Iterator;

public class FactType extends FastObject
{

   public void removeAllFrom(String className) {
      if ("fast.FactAttribute".equals(className))
      {				
         removeAllFromFactAttributes();
      }
   }
   
   /**
   Return ArrayList of all atrr names
   */
   public java.util.ArrayList arrayListOfAttrNames() {
   	java.util.ArrayList vec = new java.util.ArrayList();
   	vec.add("typeName");
   	
   	return vec;
   }

   // generic set and get methods
   public void set (String fieldName, Object value)
   {
      // typeName
      if ("typeName".equals(fieldName))
      {				
         setTypeName((String) value);
      }
      else      // serviceDesigner
      if ("serviceDesigner".equals(fieldName))
      {				
         setServiceDesigner ((fast.ServiceDesigner) value);
      }
      else      // factAttributes
      if ("factAttributes".equals(fieldName))
      {				
         addToFactAttributes ((fast.FactAttribute) value);
      }
   }

   public Object get (String fieldName)
   {
      // typeName
      if ("typeName".equals(fieldName))
      {
         return (String) getTypeName();
      }
      else      if ("serviceDesigner".equals(fieldName))
      {				
         return getServiceDesigner();
      }
      else      if ("factAttributes".equals(fieldName))
      {				
         return iteratorOfFactAttributes();
      }
      return null;
   }

   /**
    * <pre>
    *           0..1     factAttributes     0..*
    * FactType ------------------------- FactAttribute
    *           factType               factAttributes
    * </pre>
    */
   public static final String PROPERTY_FACT_ATTRIBUTES = "factAttributes";

   private FPropHashSet factAttributes;

   public boolean addToFactAttributes (FactAttribute value)
   {
      boolean changed = false;

      if (value != null)
      {
         if (this.factAttributes == null)
         {
            this.factAttributes = new FPropHashSet (this, PROPERTY_FACT_ATTRIBUTES);

         }
      
         changed = this.factAttributes.add (value);
         if (changed)
         {
            value.setFactType (this);
         }
      
      }
      return changed;
   }

   public FactType withFactAttributes (FactAttribute value)
   {
      addToFactAttributes (value);
      return this;
   }

   public FactType withoutFactAttributes (FactAttribute value)
   {
      removeFromFactAttributes (value);
      return this;
   }

   public boolean removeFromFactAttributes (FactAttribute value)
   {
      boolean changed = false;

      if ((this.factAttributes != null) && (value != null))
      {
      
         changed = this.factAttributes.remove (value);
         if (changed)
         {
            value.setFactType (null);
         }
      
      }
      return changed;
   }

   public void removeAllFromFactAttributes ()
   {
   
      FactAttribute tmpValue;

      if (factAttributes != null) {
         java.util.Vector tempSet = new java.util.Vector(factAttributes);
         Iterator iter = tempSet.iterator ();
      
         while (iter.hasNext ())
         {
            tmpValue = (FactAttribute) iter.next ();
            this.removeFromFactAttributes (tmpValue);
         }
      } 
   
   }

   public boolean hasInFactAttributes (FactAttribute value)
   {
      return ((this.factAttributes != null) &&
              (value != null) &&
              this.factAttributes.contains (value));
   }

   public Iterator iteratorOfFactAttributes ()
   {
      return ((this.factAttributes == null)
              ? FEmptyIterator.get ()
              : this.factAttributes.iterator ());
   }

   public int sizeOfFactAttributes ()
   {
      return ((this.factAttributes == null)
              ? 0
              : this.factAttributes.size ());
   }

   /**
    * <pre>
    *           0..*     factTypes     0..1
    * FactType ------------------------- ServiceDesigner
    *           factTypes               serviceDesigner
    * </pre>
    */
   public static final String PROPERTY_SERVICE_DESIGNER = "serviceDesigner";

   private ServiceDesigner serviceDesigner;

   public boolean setServiceDesigner (ServiceDesigner value)
   {
      boolean changed = false;

      if (this.serviceDesigner != value)
      {
      
         ServiceDesigner oldValue = this.serviceDesigner;
         FactType source = this;
         if (this.serviceDesigner != null)
         {
            this.serviceDesigner = null;
            oldValue.removeFromFactTypes (this);
         }
         this.serviceDesigner = value;

         if (value != null)
         {
            value.addToFactTypes (this);
         }
            getPropertyChangeSupport().firePropertyChange(PROPERTY_SERVICE_DESIGNER, oldValue, value);
         changed = true;
      
      }
      return changed;
   }

   public FactType withServiceDesigner (ServiceDesigner value)
   {
      setServiceDesigner (value);
      return this;
   }

   public ServiceDesigner getServiceDesigner ()
   {
      return this.serviceDesigner;
   }

   public static final String PROPERTY_TYPE_NAME = "typeName";

   private String typeName;

   public void setTypeName (String value)
   {
      if ( ! JavaSDM.stringEquals (this.typeName, value))
      {
         String oldValue = this.typeName;
         this.typeName = value;
         getPropertyChangeSupport().firePropertyChange(PROPERTY_TYPE_NAME, oldValue, value);
      }
   }

   public FactType withTypeName (String value)
   {
      setTypeName (value);
      return this;
   }

   public String getTypeName ()
   {
      return this.typeName;
   }

   public void removeYou()
   {
      this.removeAllFromFactAttributes ();
      this.setServiceDesigner (null);
      super.removeYou ();
   }
}


