/*
 * GWT compliant generated by Fujaba - CodeGen2 version 25.3.2009
 */

package fast;

// GWT: de.upb.tools.sdm.*

import fujaba.web.runtime.client.*;
// GWT: fast.ServiceScreen
// GWT: fast.FastObject
import fujaba.web.runtime.client.reflect.*;
import fujaba.web.runtime.client.*;
import java.util.Iterator;

public class FactPort extends FastObject
{

   public void removeAllFrom(String className) {
   }
   
   /**
   Return ArrayList of all atrr names
   */
   public java.util.ArrayList arrayListOfAttrNames() {
   	java.util.ArrayList vec = new java.util.ArrayList();
   	vec.add("name");
   	vec.add("uri");
   	vec.add("exampleValue");
   	vec.add("factType");
   	
   	return vec;
   }

   // generic set and get methods
   public void set (String fieldName, Object value)
   {
      // name
      if ("name".equals(fieldName))
      {				
         setName((String) value);
      }
      else      // uri
      if ("uri".equals(fieldName))
      {				
         setUri((String) value);
      }
      else      // exampleValue
      if ("exampleValue".equals(fieldName))
      {				
         setExampleValue((String) value);
      }
      else      // factType
      if ("factType".equals(fieldName))
      {				
         setFactType((String) value);
      }
      else      // serviceScreen
      if ("serviceScreen".equals(fieldName))
      {				
         setServiceScreen ((fast.ServiceScreen) value);
      }
      else      // serviceScreen2
      if ("serviceScreen2".equals(fieldName))
      {				
         setServiceScreen2 ((fast.ServiceScreen) value);
      }
   }

   public Object get (String fieldName)
   {
      // name
      if ("name".equals(fieldName))
      {
         return (String) getName();
      }
      else      // uri
      if ("uri".equals(fieldName))
      {
         return (String) getUri();
      }
      else      // exampleValue
      if ("exampleValue".equals(fieldName))
      {
         return (String) getExampleValue();
      }
      else      // factType
      if ("factType".equals(fieldName))
      {
         return (String) getFactType();
      }
      else      if ("serviceScreen".equals(fieldName))
      {				
         return getServiceScreen();
      }
      else      if ("serviceScreen2".equals(fieldName))
      {				
         return getServiceScreen2();
      }
      return null;
   }

   public static final String PROPERTY_EXAMPLE_VALUE = "exampleValue";

   private String exampleValue;

   public void setExampleValue (String value)
   {
      if ( ! JavaSDM.stringEquals (this.exampleValue, value))
      {
         String oldValue = this.exampleValue;
         this.exampleValue = value;
         getPropertyChangeSupport().firePropertyChange(PROPERTY_EXAMPLE_VALUE, oldValue, value);
      }
   }

   public FactPort withExampleValue (String value)
   {
      setExampleValue (value);
      return this;
   }

   public String getExampleValue ()
   {
      return this.exampleValue;
   }

   public static final String PROPERTY_FACT_TYPE = "factType";

   private String factType;

   public void setFactType (String value)
   {
      if ( ! JavaSDM.stringEquals (this.factType, value))
      {
         String oldValue = this.factType;
         this.factType = value;
         getPropertyChangeSupport().firePropertyChange(PROPERTY_FACT_TYPE, oldValue, value);
      }
   }

   public FactPort withFactType (String value)
   {
      setFactType (value);
      return this;
   }

   public String getFactType ()
   {
      return this.factType;
   }

   public static final String PROPERTY_NAME = "name";

   private String name;

   public void setName (String value)
   {
      if ( ! JavaSDM.stringEquals (this.name, value))
      {
         String oldValue = this.name;
         this.name = value;
         getPropertyChangeSupport().firePropertyChange(PROPERTY_NAME, oldValue, value);
      }
   }

   public FactPort withName (String value)
   {
      setName (value);
      return this;
   }

   public String getName ()
   {
      return this.name;
   }

   /**
    * <pre>
    *           0..*     postconditions     0..1
    * FactPort ------------------------- ServiceScreen
    *           postconditions               serviceScreen2
    * </pre>
    */
   public static final String PROPERTY_SERVICE_SCREEN2 = "serviceScreen2";

   private ServiceScreen serviceScreen2;

   public boolean setServiceScreen2 (ServiceScreen value)
   {
      boolean changed = false;

      if (this.serviceScreen2 != value)
      {
      
         ServiceScreen oldValue = this.serviceScreen2;
         FactPort source = this;
         if (this.serviceScreen2 != null)
         {
            this.serviceScreen2 = null;
            oldValue.removeFromPostconditions (this);
         }
         this.serviceScreen2 = value;

         if (value != null)
         {
            value.addToPostconditions (this);
         }
            getPropertyChangeSupport().firePropertyChange(PROPERTY_SERVICE_SCREEN2, oldValue, value);
         changed = true;
      
      }
      return changed;
   }

   public FactPort withServiceScreen2 (ServiceScreen value)
   {
      setServiceScreen2 (value);
      return this;
   }

   public ServiceScreen getServiceScreen2 ()
   {
      return this.serviceScreen2;
   }

   /**
    * <pre>
    *           0..*     preconditions     0..1
    * FactPort ------------------------- ServiceScreen
    *           preconditions               serviceScreen
    * </pre>
    */
   public static final String PROPERTY_SERVICE_SCREEN = "serviceScreen";

   private ServiceScreen serviceScreen;

   public boolean setServiceScreen (ServiceScreen value)
   {
      boolean changed = false;

      if (this.serviceScreen != value)
      {
      
         ServiceScreen oldValue = this.serviceScreen;
         FactPort source = this;
         if (this.serviceScreen != null)
         {
            this.serviceScreen = null;
            oldValue.removeFromPreconditions (this);
         }
         this.serviceScreen = value;

         if (value != null)
         {
            value.addToPreconditions (this);
         }
            getPropertyChangeSupport().firePropertyChange(PROPERTY_SERVICE_SCREEN, oldValue, value);
         changed = true;
      
      }
      return changed;
   }

   public FactPort withServiceScreen (ServiceScreen value)
   {
      setServiceScreen (value);
      return this;
   }

   public ServiceScreen getServiceScreen ()
   {
      return this.serviceScreen;
   }

   public static final String PROPERTY_URI = "uri";

   private String uri;

   public void setUri (String value)
   {
      if ( ! JavaSDM.stringEquals (this.uri, value))
      {
         String oldValue = this.uri;
         this.uri = value;
         getPropertyChangeSupport().firePropertyChange(PROPERTY_URI, oldValue, value);
      }
   }

   public FactPort withUri (String value)
   {
      setUri (value);
      return this;
   }

   public String getUri ()
   {
      return this.uri;
   }

   public void removeYou()
   {
      this.setServiceScreen2 (null);
      this.setServiceScreen (null);
      super.removeYou ();
   }
}


