/*
 * GWT compliant generated by Fujaba - CodeGen2 version 25.3.2009
 */

package fast;

// GWT: fujaba.web.runtime.client.CoobraRoot

import fujaba.web.runtime.client.CoobraRoot;
// GWT: de.upb.tools.sdm.*

import fujaba.web.runtime.client.*;
// GWT: de.upb.tools.pcs.PropertyChangeClient

import fujaba.web.runtime.client.PropertyChangeClient;
// GWT: java.beans.PropertyChangeSupport

// GWT: java.beans.PropertyChangeListener

// GWT: fujaba.web.runtime.client.CObject

import fujaba.web.runtime.client.CObject;
import fujaba.web.runtime.client.reflect.*;
import fujaba.web.runtime.client.*;
import java.util.Iterator;

public class FastObject extends CObject implements PropertyChangeClient
{

   public void removeAllFrom(String className) {
   }
   
   /**
   Return ArrayList of all atrr names
   */
   public java.util.ArrayList arrayListOfAttrNames() {
   	java.util.ArrayList vec = new java.util.ArrayList();
   	
   	return vec;
   }

   // generic set and get methods
   public void set (String fieldName, Object value)
   {
   }

   public Object get (String fieldName)
   {
      return null;
   }
	protected final PropertyChangeSupport listeners = new PropertyChangeSupport(this);

	public void addPropertyChangeListener(PropertyChangeListener listener)
	{
		getPropertyChangeSupport().addPropertyChangeListener(listener);
	}

	public void removePropertyChangeListener(PropertyChangeListener listener)
	{
		getPropertyChangeSupport().removePropertyChangeListener(listener);
	}

	public void addPropertyChangeListener(String property, PropertyChangeListener listener)
	{
		getPropertyChangeSupport().addPropertyChangeListener(property, listener);
	}

	public void removePropertyChangeListener(String property, PropertyChangeListener listener)
	{
		getPropertyChangeSupport().removePropertyChangeListener(property, listener);
	}

	public PropertyChangeSupport getPropertyChangeSupport()
	{
		return listeners;
	}


   public  FastObject ()
   {
      boolean fujaba__Success = false;
      CoobraRoot coobra = null;

      // story pattern successor
      try 
      {
         fujaba__Success = false; 

         // create object coobra
         coobra = CoobraRoot.get();

         // create link sharedObjects from coobra to this
         coobra.addToSharedObjects (this);

         fujaba__Success = true;
      }
      catch ( JavaSDMException fujaba__InternalException )
      {
         fujaba__Success = false;
      }

      return ;
   }

   public void removeYou()
   {
   }
}


