#!/usr/bin/env python

import sys, os
from fast.templates.js_list import file_list

final_file_name = "media/js/fast.js"

def which(program):
    def is_exe(fpath):
        return os.path.exists(fpath) and os.access(fpath, os.X_OK)

    fpath, fname = os.path.split(program)
    if fpath:
        if is_exe(program):
            return program
    else:
        for path in os.environ["PATH"].split(os.pathsep):
            exe_file = os.path.join(path, program)
            if is_exe(exe_file):
                return exe_file

    return None

def write_file(output_file_name):
    sys.stdout.write ("Creating %s..." % output_file_name)
    sys.stdout.flush()

    try:
        res = open(output_file_name, 'w')

        for file_name in file_list:
           file = open(os.path.join("media", "js", file_name), 'r')

           res.write(file.read())
           res.write("\n")

           file.close()

        res.close()
    except Exception, e:
        print e

    if java_available:
      os.system("java -jar compressor.jar " + output_file_name + " -o " + output_file_name)

    sys.stdout.write(" Done\n")

def build_js_list(output_file_name):
    sys.stdout.write ("Creating %s..." % output_file_name)
    sys.stdout.flush()

    try:
        res = open(output_file_name, 'w')

        res.write('<!-- This is an autogenerated list of javascript files, please\n' +
                  '     edit the js_list.py file and run compress.py on the project\'s\n' +
                  '     root forlder for updating it. -->\n')

        for file_name in file_list:
           res.write('<script type="text/javascript" src="{{ MEDIA_URL }}/js/%s"></script>\n' % file_name)

        res.close()
    except Exception, e:
        print e

    sys.stdout.write(" Done\n")


#Main
java_available = which('java') != None
if not java_available:
    sys.stdout.write('Warning: java command not found. JavaScript files will be not compressed')
    sys.stdout.write('\n')

sys.stdout.write('\n')

build_js_list('fast/templates/js_list.html')

sys.stdout.write("\n")

write_file('media/js/fast.js')

sys.stdout.write("\n")

