/*
 * GWT compliant generated by Fujaba - CodeGen2 version 03.12.2009
 */

package fast.facttool.client;

import fujaba.web.runtime.client.CObject;
import com.google.gwt.user.client.ui.TextArea;
import com.google.gwt.user.client.ui.Panel;
import fujaba.web.runtime.client.reflect.*;
import fujaba.web.runtime.client.*;
import java.util.*;
import com.google.gwt.event.dom.client.ClickHandler;
import com.google.gwt.event.dom.client.ClickEvent;




public class AttributeTextArea
{

   public void removeAllFrom(String className) 
   {
   }
   
   /**
   Return ArrayList of all atrr names
   */
   public java.util.ArrayList arrayListOfAttrNames() 
   {
      java.util.ArrayList vec = new java.util.ArrayList();
      vec.add("attrName");
   	
      return vec;
   }

   // generic set and get methods
   public void set (String fieldName, Object value)
   {
      // attrName
      if ("attrName".equals(fieldName)){
         setAttrName((String) value);
      }   }  

   public void add (String fieldName, Object value)
   {
      set (fieldName, value);
   }

   public Object get (String fieldName)
   {
      // attrName
      if ("attrName".equals(fieldName)){
         return (String) getAttrName();
      }
      return null;
   }

   // create attributes for all objects in all states of this statechart
   private TextArea area;

   public void start()
   {
      initStateChart();
      // call doAction on initial state
      build.doAction();
   }

   public void start(FAction parent)
   {
      initStateChart();
      //set parent of rootState
      build.setToParent(parent);
      // call doAction on rootState
      build.doAction();
   }

   // GWT statechart code
   public void initStateChart()
   {
      if(build != null)
         return;

      areaHandler = new AreaHandler ();
      attrListener = new AttrListener ();
      build = new Build ();
      // NONE

      //build.addToFollowers("area.change", areaHandler);
      // NONE

      //build.addToFollowers("object.change", attrListener);
   }


   private AreaHandler areaHandler;
   public class AreaHandler extends FAction
   {
       public void doAction()
       {
   		 boolean fujaba__Success = false;

         // story pattern storypatternwiththis
         try 
         {
            fujaba__Success = false; 

            // check object object is really bound
            JavaSDM.ensure ( object != null );
            // collabStat call
            object.set(attrName, area.getText());
            fujaba__Success = true;
         }
         catch ( JavaSDMException fujaba__InternalException )
         {
            fujaba__Success = false;
         }



       }

   }

   private AttrListener attrListener;
   public class AttrListener extends FAction
   {
       public void doAction()
       {
   		 boolean fujaba__Success = false;

         // story pattern storypatternwiththis
         try 
         {
            fujaba__Success = false; 

            // check object area is really bound
            JavaSDM.ensure ( area != null );
            // assign attribute area
            area.setText ((String) object.get(attrName));
            fujaba__Success = true;
         }
         catch ( JavaSDMException fujaba__InternalException )
         {
            fujaba__Success = false;
         }



       }

   }

   private Build build;
   public class Build extends FAction
   {
       public void doAction()
       {
   		 boolean fujaba__Success = false;

         // story pattern storypatternwiththis
         try 
         {
            fujaba__Success = false; 

            // check object object is really bound
            JavaSDM.ensure ( object != null );
            // check object parent is really bound
            JavaSDM.ensure ( parent != null );
            // create object area
            area = new TextArea ( );

            // assign attribute area
            area.setText ((String) object.get(attrName));
            // create link widget from parent to area
            parent.add (area);

            // collabStat call
            area.setSize("10cm", "3cm");
            fujaba__Success = true;
         }
         catch ( JavaSDMException fujaba__InternalException )
         {
            fujaba__Success = false;
         }


         object.addPropertyChangeListener(attrListener);
         area.addChangeHandler(areaHandler);

       }

   }

   // my style test for method.vm


   // my style test for method.vm


   private String attrName;

   public void setAttrName (String value)
   {
      this.attrName = value;
   }

   public AttributeTextArea withAttrName (String value)
   {
      setAttrName (value);
      return this;
   }

   public String getAttrName ()
   {
      return this.attrName;
   }
   public void start (Panel parent , CObject object )
   { 
      // copy parameters to attributes
      this.parent = parent;
      this.object = object;
      start();
   }

   // attributes for action container method parameters 
   public Panel parent;
   public CObject object;


   public void removeYou()
   {
   }
}


