/**
 * Copyright (c) 2008-2011, FAST Consortium
 * 
 * This file is part of FAST Platform.
 * 
 * FAST Platform is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Affero General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 * 
 * FAST Platform is distributed in the hope that it will be useful, but
 * WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY
 * or FITNESS FOR A PARTICULAR PURPOSE. See the GNU Affero General Public
 * License for more details.
 * 
 * You should have received a copy of the GNU Affero General Public License
 * along with FAST Platform. If not, see <http://www.gnu.org/licenses/>.
 * 
 * Info about members and contributors of the FAST Consortium
 * is available at http://fast.morfeo-project.eu
 *
 **/
/*
 * GWT compliant generated by Fujaba - CodeGen2 version 03.12.2009
 */

package fast.facttool.client;

import com.google.gwt.user.client.ui.TreeItem;
import fast.common.client.FactExample;
import com.google.gwt.user.client.ui.HorizontalPanel;
import fast.facttool.client.AttributeTextArea;
import com.google.gwt.user.client.ui.Button;
import fujaba.web.runtime.client.reflect.*;
import fujaba.web.runtime.client.*;
import java.util.*;
import com.google.gwt.event.dom.client.ClickHandler;
import com.google.gwt.event.dom.client.ClickEvent;




public class ExampleValuesPanel implements PropertyChangeClient
{

   public void removeAllFrom(String className) 
   {
   }
   
   /**
   Return ArrayList of all atrr names
   */
   public java.util.ArrayList arrayListOfAttrNames() 
   {
      java.util.ArrayList vec = new java.util.ArrayList();
   	
      return vec;
   }

   // generic set and get methods
   public void set (String fieldName, Object value)
   {
   }  

   public void add (String fieldName, Object value)
   {
      set (fieldName, value);
   }

   public Object get (String fieldName)
   {
      return null;
   }
	protected final PropertyChangeSupport listeners = new PropertyChangeSupport(this);

	public void addPropertyChangeListener(PropertyChangeListener listener)
	{
		getPropertyChangeSupport().addPropertyChangeListener(listener);
	}

	public void removePropertyChangeListener(PropertyChangeListener listener)
	{
		getPropertyChangeSupport().removePropertyChangeListener(listener);
	}

	public void addPropertyChangeListener(String property, PropertyChangeListener listener)
	{
		getPropertyChangeSupport().addPropertyChangeListener(property, listener);
	}

	public void removePropertyChangeListener(String property, PropertyChangeListener listener)
	{
		getPropertyChangeSupport().removePropertyChangeListener(property, listener);
	}

	public PropertyChangeSupport getPropertyChangeSupport()
	{
		return listeners;
	}


   // create attributes for all objects in all states of this statechart
   private AttributeTextArea exampleValTextBox;
   private Button exampleValDeleteButton;
   private HorizontalPanel factExamplePanel;

   private TreeItem exampleItem;

   public void start()
   {
      initStateChart();
      // call doAction on initial state
      build.doAction();
   }

   public void start(FAction parent)
   {
      initStateChart();
      //set parent of rootState
      build.setToParent(parent);
      // call doAction on rootState
      build.doAction();
   }

   // GWT statechart code
   public void initStateChart()
   {
      if(build != null)
         return;

      addToTree = new AddToTree ();
      build = new Build ();
      exampleValDeleteButtonHandler = new ExampleValDeleteButtonHandler ();
      // NONE

      //build.addToFollowers("auto", addToTree);
      // NONE

      //build.addToFollowers("exampleValDeleteButton.click", exampleValDeleteButtonHandler);
   }


   private AddToTree addToTree;
   public class AddToTree extends FAction
   {
       public void doAction()
       {
   		 boolean fujaba__Success = false;

         // story pattern storypatternwiththis
         try 
         {
            fujaba__Success = false; 

            // create object exampleItem
            exampleItem = parent.addItem(factExamplePanel);

            fujaba__Success = true;
         }
         catch ( JavaSDMException fujaba__InternalException )
         {
            fujaba__Success = false;
         }



       }

   }

   private Build build;
   public class Build extends FAction
   {
       public void doAction()
       {
   		 boolean fujaba__Success = false;

         // story pattern storypatternwiththis
         try 
         {
            fujaba__Success = false; 

            // check object factExample is really bound
            JavaSDM.ensure ( factExample != null );
            // check object parent is really bound
            JavaSDM.ensure ( parent != null );
            // create object factExamplePanel
            factExamplePanel = new HorizontalPanel ( );

            // create object exampleValTextBox
            exampleValTextBox = new AttributeTextArea ( );

            // create object exampleValDeleteButton
            exampleValDeleteButton = new Button ( );

            // assign attribute exampleValTextBox
            exampleValTextBox.setAttrName ("json");
            // assign attribute exampleValDeleteButton
            exampleValDeleteButton.setText ("delete");
            // collabStat call
            exampleValTextBox.start(factExamplePanel, factExample);
            // collabStat call
            factExamplePanel.add(exampleValDeleteButton);
            // collabStat call
            exampleValDeleteButton.setStyleName("fastButton");
            fujaba__Success = true;
         }
         catch ( JavaSDMException fujaba__InternalException )
         {
            fujaba__Success = false;
         }


         exampleValDeleteButton.addClickHandler(exampleValDeleteButtonHandler);

   		 if( autoGuardBuild1 == null)
   		 {
   			 autoGuardBuild1 = new AutoGuardBuild1();
   			 autoGuardBuild1.setSource(build);
   			 autoGuardBuild1.setTarget(addToTree);
   			 build.addToAutoTransitions(autoGuardBuild1.toString(), autoGuardBuild1);
   		 }

   		 doAuto();
       }

      private AutoGuardBuild1 autoGuardBuild1;
      private class AutoGuardBuild1 extends FGuard
      {
      }

   }

   private ExampleValDeleteButtonHandler exampleValDeleteButtonHandler;
   public class ExampleValDeleteButtonHandler extends FAction
   {
       public void doAction()
       {
   		 boolean fujaba__Success = false;

         // story pattern storypatternwiththis
         try 
         {
            fujaba__Success = false; 

            // check object exampleItem is really bound
            JavaSDM.ensure ( exampleItem != null );
            // check object factExample is really bound
            JavaSDM.ensure ( factExample != null );
            // collabStat call
            factExample.removeYou();
            // collabStat call
            exampleItem.remove();
            fujaba__Success = true;
         }
         catch ( JavaSDMException fujaba__InternalException )
         {
            fujaba__Success = false;
         }



       }

   }

   // my style test for method.vm


   // my style test for method.vm

   public void start (FactExample factExample , TreeItem parent )
   { 
      // copy parameters to attributes
      this.factExample = factExample;
      this.parent = parent;
      start();
   }

   // attributes for action container method parameters 
   public FactExample factExample;
   public TreeItem parent;


   public void removeYou()
   {
   }
}


