/*
 * GWT compliant generated by Fujaba - CodeGen2 version 03.12.2009
 */

package fast.facttool.client;

import fujaba.web.runtime.client.FTest;
import fast.facttool.client.FactEditor;
import com.google.gwt.core.client.EntryPoint;
import fujaba.web.runtime.client.reflect.*;
import fujaba.web.runtime.client.*;
import java.util.*;
import com.google.gwt.event.dom.client.ClickHandler;
import com.google.gwt.event.dom.client.ClickEvent;


 //test

public class FactTool implements EntryPoint
{

   public void removeAllFrom(String className) 
   {
   }
   
   /**
   Return ArrayList of all atrr names
   */
   public java.util.ArrayList arrayListOfAttrNames() 
   {
      java.util.ArrayList vec = new java.util.ArrayList();
   	
      return vec;
   }

   // generic set and get methods
   public void set (String fieldName, Object value)
   {
   }  

   public void add (String fieldName, Object value)
   {
      set (fieldName, value);
   }

   public Object get (String fieldName)
   {
      return null;
   }
   public void onModuleLoad ()
   { 
      boolean fujaba__Success = false;
      FactEditor editor = null;

      // story pattern storypatternwiththis
      try 
      {
         fujaba__Success = false; 

         // create object editor
         editor = new FactEditor ( );

         // collabStat call
         FTest.init();
         // collabStat call
         FTest.assertTrue(true, "module FactTool reached");
         // collabStat call
         editor.start();
         fujaba__Success = true;
      }
      catch ( JavaSDMException fujaba__InternalException )
      {
         fujaba__Success = false;
      }

      return ;
   }

   public void removeYou()
   {
   }
}


