/**
 * Copyright (c) 2008-2011, FAST Consortium
 * 
 * This file is part of FAST Platform.
 * 
 * FAST Platform is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Affero General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 * 
 * FAST Platform is distributed in the hope that it will be useful, but
 * WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY
 * or FITNESS FOR A PARTICULAR PURPOSE. See the GNU Affero General Public
 * License for more details.
 * 
 * You should have received a copy of the GNU Affero General Public License
 * along with FAST Platform. If not, see <http://www.gnu.org/licenses/>.
 * 
 * Info about members and contributors of the FAST Consortium
 * is available at http://fast.morfeo-project.eu
 *
 **/
/*
 * GWT compliant generated by Fujaba - CodeGen2 version 03.12.2009
 */

package fast.facttool.client;

import fujaba.web.runtime.client.FTest;
import de.uni_kassel.webcoobra.client.CoobraRoot;
import java.util.*;
import fast.common.client.ServiceDesigner;
import fast.facttool.client.FactTypeTree;
import com.google.gwt.json.client.JSONArray;
import com.google.gwt.json.client.JSONParser;
import fast.servicescreen.client.RequestServiceAsync;
import com.google.gwt.core.client.GWT;
import fast.servicescreen.client.RequestService;
import de.uni_kassel.webcoobra.client.CoobraServiceAsync;
import fast.common.client.BuildingBlock;
import de.uni_kassel.webcoobra.client.DataLoadTimer;
import fast.common.client.ServiceScreenModel;
import de.uni_kassel.webcoobra.client.*;
import fujaba.web.runtime.client.reflect.*;
import fujaba.web.runtime.client.*;
import java.util.*;
import com.google.gwt.event.dom.client.ClickHandler;
import com.google.gwt.event.dom.client.ClickEvent;




public class FactEditor implements PropertyChangeClient
{

   public void removeAllFrom(String className) 
   {
   }
   
   /**
   Return ArrayList of all atrr names
   */
   public java.util.ArrayList arrayListOfAttrNames() 
   {
      java.util.ArrayList vec = new java.util.ArrayList();
   	
      return vec;
   }

   // generic set and get methods
   public void set (String fieldName, Object value)
   {
   }  

   public void add (String fieldName, Object value)
   {
      set (fieldName, value);
   }

   public Object get (String fieldName)
   {
      return null;
   }
	protected final PropertyChangeSupport listeners = new PropertyChangeSupport(this);

	public void addPropertyChangeListener(PropertyChangeListener listener)
	{
		getPropertyChangeSupport().addPropertyChangeListener(listener);
	}

	public void removePropertyChangeListener(PropertyChangeListener listener)
	{
		getPropertyChangeSupport().removePropertyChangeListener(listener);
	}

	public void addPropertyChangeListener(String property, PropertyChangeListener listener)
	{
		getPropertyChangeSupport().addPropertyChangeListener(property, listener);
	}

	public void removePropertyChangeListener(String property, PropertyChangeListener listener)
	{
		getPropertyChangeSupport().removePropertyChangeListener(property, listener);
	}

	public PropertyChangeSupport getPropertyChangeSupport()
	{
		return listeners;
	}


   // create attributes for all objects in all states of this statechart
   private CoobraServiceAsync coobraService;
   private CoobraRoot coobraRoot;
   private RequestService fixMe;
   private Object _TmpObject;
   private FactTypeTree factTypeTree;
   private GWT gwt;
   private ServiceDesigner designer;
   private JSONArray conceptArray;
   private RequestServiceAsync getConceptService;
   private DataLoadTimer dataLoadTimer;
   private Iterator fujaba__IterCoobraRootToDesigner;
   private ServiceScreenModel modelRoot;

   public void start()
   {
      initStateChart();
      // call doAction on initial state
      init.doAction();
   }

   public void start(FAction parent)
   {
      initStateChart();
      //set parent of rootState
      init.setToParent(parent);
      // call doAction on rootState
      init.doAction();
   }

   // GWT statechart code
   public void initStateChart()
   {
      if(init != null)
         return;

      buildModel = new BuildModel ();
      conceptCallback = new ConceptCallback ();
      getConceptsFromCatalogue = new GetConceptsFromCatalogue ();
      init = new Init ();
      loadData = new LoadData ();
      // success
      init.setToSuccess(loadData);
      // success
      loadData.setToSuccess(getConceptsFromCatalogue);
      // success
      conceptCallback.setToSuccess(buildModel);
      // success
      getConceptsFromCatalogue.setToSuccess(conceptCallback);
   }


   // my style test for method.vm


   // my style test for method.vm


   // my style test for method.vm


   // my style test for method.vm


   private BuildModel buildModel;
   public class BuildModel extends FAction
   {
       public void doAction()
       {
   		 boolean fujaba__Success = false;

         // story pattern storypatternwiththis
         try 
         {
            fujaba__Success = false; 

            // check object coobraRoot is really bound
            JavaSDM.ensure ( coobraRoot != null );
            // iterate to-many link sharedObjects from coobraRoot to designer
            fujaba__Success = false;
            fujaba__IterCoobraRootToDesigner = coobraRoot.iteratorOfSharedObjects ();

            while ( !(fujaba__Success) && fujaba__IterCoobraRootToDesigner.hasNext () )
            {
               try
               {
                  _TmpObject =  fujaba__IterCoobraRootToDesigner.next ();

                  // ensure correct type and really bound of object designer
                  JavaSDM.ensure ( _TmpObject instanceof ServiceDesigner );
                  designer = (ServiceDesigner) _TmpObject;


                  fujaba__Success = true;
               }
               catch ( JavaSDMException fujaba__InternalException )
               {
                  fujaba__Success = false;
               }
            }
            JavaSDM.ensure (fujaba__Success);
            // create object factTypeTree
            factTypeTree = new FactTypeTree ( );

            // collabStat call
            FTest.assertTrue(true, "build model reached " + designer);
            // collabStat call
            factTypeTree.start ();
            fujaba__Success = true;
         }
         catch ( JavaSDMException fujaba__InternalException )
         {
            fujaba__Success = false;
         }



       }

   }

   private ConceptCallback conceptCallback;
   public class ConceptCallback extends FAction
   {
       public void doAction()
       {
   		 boolean fujaba__Success = false;

         // story pattern storypatternwiththis
         try 
         {
            fujaba__Success = false; 

            // create object conceptArray
            conceptArray = JSONParser.parse((String)resultValue).isArray();

            // create object fixme2
            // fixme2 = null;

            fujaba__Success = true;
         }
         catch ( JavaSDMException fujaba__InternalException )
         {
            fujaba__Success = false;
         }



       }

   }

   private GetConceptsFromCatalogue getConceptsFromCatalogue;
   public class GetConceptsFromCatalogue extends FAction
   {
       public void doAction()
       {
   		 boolean fujaba__Success = false;

         // story pattern storypatternwiththis
         try 
         {
            fujaba__Success = false; 

            // create object getConceptService
            getConceptService = GWT.create(RequestService.class);

            // create object gwt
            gwt = null;

            // create object fixMe
            fixMe = null;

            // collabStat call
            getConceptService.sendHttpRequest_GET("http://localhost:8080/Catalogue-1/concepts", null, conceptCallback);
            fujaba__Success = true;
         }
         catch ( JavaSDMException fujaba__InternalException )
         {
            fujaba__Success = false;
         }



       }

   }

   private Init init;
   public class Init extends FAction
   {
       public void doAction()
       {
   		 boolean fujaba__Success = false;

         // story pattern storypatternwiththis
         try 
         {
            fujaba__Success = false; 

            coobraService = CoobraService.Util.getDefault();

            // check object coobraService is really bound
            JavaSDM.ensure ( coobraService != null );
            // collabStat call
            FTest.assertTrue(true, "inital statechart state reached");
            // collabStat call
            coobraService.openSession("login", "pass2", "ServiceScreenRepository.cdr", this);
            fujaba__Success = true;
         }
         catch ( JavaSDMException fujaba__InternalException )
         {
            fujaba__Success = false;
         }



       }

   }

   private LoadData loadData;
   public class LoadData extends FAction
   {
       public void doAction()
       {
   		 boolean fujaba__Success = false;

         // story pattern storypatternwiththis
         try 
         {
            fujaba__Success = false; 

            coobraRoot = CoobraRoot.get();

            // check object coobraRoot is really bound
            JavaSDM.ensure ( coobraRoot != null );
            dataLoadTimer = DataLoadTimer.get();

            // check object dataLoadTimer is really bound
            JavaSDM.ensure ( dataLoadTimer != null );
            // create object modelRoot
            modelRoot = new ServiceScreenModel ( );

            // assign attribute coobraRoot
            coobraRoot.setAutoLoadData (true);
            // assign attribute coobraRoot
            coobraRoot.setSendBufferTimeout (500);
            // assign attribute coobraRoot
            coobraRoot.setEnableSendBuffer (true);
            // assign attribute coobraRoot
            coobraRoot.setSessionId ((String) this.resultValue);
            // collabStat call
            FTest.assertTrue(true, "load data reached");
            // collabStat call
            modelRoot.registerModelRoot();
            // collabStat call
            dataLoadTimer.run(getConceptsFromCatalogue, null);
            fujaba__Success = true;
         }
         catch ( JavaSDMException fujaba__InternalException )
         {
            fujaba__Success = false;
         }



       }

   }

   public void removeYou()
   {
   }
}


