/**
 * Copyright (c) 2008-2011, FAST Consortium
 * 
 * This file is part of FAST Platform.
 * 
 * FAST Platform is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Affero General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 * 
 * FAST Platform is distributed in the hope that it will be useful, but
 * WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY
 * or FITNESS FOR A PARTICULAR PURPOSE. See the GNU Affero General Public
 * License for more details.
 * 
 * You should have received a copy of the GNU Affero General Public License
 * along with FAST Platform. If not, see <http://www.gnu.org/licenses/>.
 * 
 * Info about members and contributors of the FAST Consortium
 * is available at http://fast.morfeo-project.eu
 *
 **/
/*
 * GWT compliant generated by Fujaba - CodeGen2 version 03.12.2009
 */

package fast.common.client;

import fast.common.client.FactType;
import fast.common.client.FastObject;
import fujaba.web.runtime.client.reflect.*;
import fujaba.web.runtime.client.*;
import java.util.*;
import com.google.gwt.event.dom.client.ClickHandler;
import com.google.gwt.event.dom.client.ClickEvent;




public class FactExample extends FastObject
{

   public void removeAllFrom(String className) 
   {
   }
   
   /**
   Return ArrayList of all atrr names
   */
   public java.util.ArrayList arrayListOfAttrNames() 
   {
      java.util.ArrayList vec = new java.util.ArrayList();
      vec.add("json");
   	
      return vec;
   }

   // generic set and get methods
   public void set (String fieldName, Object value)
   {
      // json
      if ("json".equals(fieldName)){
         setJson((String) value);
      }  else// factType
      if ("factType".equals(fieldName)){
         setFactType ((fast.common.client.FactType) value);
      }   }  

   public void add (String fieldName, Object value)
   {
      set (fieldName, value);
   }

   public Object get (String fieldName)
   {
      // json
      if ("json".equals(fieldName)){
         return (String) getJson();
      }
      else      if ("factType".equals(fieldName))
      {
         return getFactType();
      }
      return null;
   }

   /**
    * <pre>
    *           0..*     factExamples     0..1
    * FactExample ------------------------- FactType
    *           factExamples               factType
    * </pre>
    */
   public static final String PROPERTY_FACT_TYPE = "factType";

   private FactType factType;

   public boolean setFactType (FactType value)
   {
      boolean changed = false;

      if (this.factType != value)
      {
      
         FactType oldValue = this.factType;
         FactExample source = this;
         if (this.factType != null)
         {
            this.factType = null;
            oldValue.removeFromFactExamples (this);
         }
         this.factType = value;

         if (value != null)
         {
            value.addToFactExamples (this);
         }
            getPropertyChangeSupport().firePropertyChange(PROPERTY_FACT_TYPE, oldValue, value);
         changed = true;
      
      }
      return changed;
   }

   public FactExample withFactType (FactType value)
   {
      setFactType (value);
      return this;
   }

   public FactType getFactType ()
   {
      return this.factType;
   }

   public static final String PROPERTY_JSON = "json";

   private String json;

   public void setJson (String value)
   {
      if ( ! JavaSDM.stringEquals (this.json, value))
      {
         String oldValue = this.json;
         this.json = value;
         getPropertyChangeSupport().firePropertyChange(PROPERTY_JSON, oldValue, value);
      }
   }

   public FactExample withJson (String value)
   {
      setJson (value);
      return this;
   }

   public String getJson ()
   {
      return this.json;
   }

   public void removeYou()
   {
      this.setFactType (null);
      super.removeYou ();
   }
}


