/*
 * GWT compliant generated by Fujaba - CodeGen2 version 03.12.2009
 */

package fast.common.client;

import fast.common.client.FactType;
import fujaba.web.runtime.client.reflect.*;
import fujaba.web.runtime.client.*;
import java.util.*;
import com.google.gwt.event.dom.client.ClickHandler;
import com.google.gwt.event.dom.client.ClickEvent;




public class FactTag implements PropertyChangeClient
{

   public void removeAllFrom(String className) 
   {
   }
   
   /**
   Return ArrayList of all atrr names
   */
   public java.util.ArrayList arrayListOfAttrNames() 
   {
      java.util.ArrayList vec = new java.util.ArrayList();
      vec.add("value");
   	
      return vec;
   }

   // generic set and get methods
   public void set (String fieldName, Object value)
   {
      // value
      if ("value".equals(fieldName)){				
         setValue((String) value);
      }//( toMany false || toMany2 true || qualified $qualified || 
// internalQualified false ||  
// role.Qualifier $role.Qualifier || ordered false || sorted false)
 //2[! (  ( toMany || !toMany2) && !( toMany && toMany2)  && role.Qualifier  ) ]
//2.2[ !( qualified && !internalQualified ) ]
 else// owner
      if ("owner".equals(fieldName)){				
         setOwner ((fast.common.client.FactType) value);
      }   }  

   public void add (String fieldName, Object value)
   {
      set (fieldName, value);
   }

   public Object get (String fieldName)
   {
      // value
      if ("value".equals(fieldName)){
         return (String) getValue();
      }
      else      if ("owner".equals(fieldName))
      {				
         return getOwner();
      }
      return null;
   }
	protected final PropertyChangeSupport listeners = new PropertyChangeSupport(this);

	public void addPropertyChangeListener(PropertyChangeListener listener)
	{
		getPropertyChangeSupport().addPropertyChangeListener(listener);
	}

	public void removePropertyChangeListener(PropertyChangeListener listener)
	{
		getPropertyChangeSupport().removePropertyChangeListener(listener);
	}

	public void addPropertyChangeListener(String property, PropertyChangeListener listener)
	{
		getPropertyChangeSupport().addPropertyChangeListener(property, listener);
	}

	public void removePropertyChangeListener(String property, PropertyChangeListener listener)
	{
		getPropertyChangeSupport().removePropertyChangeListener(property, listener);
	}

	public PropertyChangeSupport getPropertyChangeSupport()
	{
		return listeners;
	}


   /**
    * <pre>
    *           0..*     factTags     0..1
    * FactTag ------------------------- FactType
    *           factTags               owner
    * </pre>
    */
   public static final String PROPERTY_OWNER = "owner";

   private FactType owner;

   public boolean setOwner (FactType value)
   {
      boolean changed = false;

      if (this.owner != value)
      {
      
         FactType oldValue = this.owner;
         FactTag source = this;
         if (this.owner != null)
         {
            this.owner = null;
            oldValue.removeFromFactTags (this);
         }
         this.owner = value;

         if (value != null)
         {
            value.addToFactTags (this);
         }
            getPropertyChangeSupport().firePropertyChange(PROPERTY_OWNER, oldValue, value);
         changed = true;
      
      }
      return changed;
   }

   public FactTag withOwner (FactType value)
   {
      setOwner (value);
      return this;
   }

   public FactType getOwner ()
   {
      return this.owner;
   }

   public static final String PROPERTY_VALUE = "value";

   private String value;

   public void setValue (String value)
   {
      if ( ! JavaSDM.stringEquals (this.value, value))
      {
         String oldValue = this.value;
         this.value = value;
         getPropertyChangeSupport().firePropertyChange(PROPERTY_VALUE, oldValue, value);
      }
   }

   public FactTag withValue (String value)
   {
      setValue (value);
      return this;
   }

   public String getValue ()
   {
      return this.value;
   }

   public void removeYou()
   {
      this.setOwner (null);
   }
}


