/*
 * GWT compliant generated by Fujaba - CodeGen2 version 03.12.2009
 */

package fast.common.client;

import fast.common.client.BuildingBlock;
import fast.common.client.FastObject;
import fujaba.web.runtime.client.reflect.*;
import fujaba.web.runtime.client.*;
import java.util.*;
import com.google.gwt.event.dom.client.ClickHandler;
import com.google.gwt.event.dom.client.ClickEvent;




public class FactPort extends FastObject
{

   public void removeAllFrom(String className) 
   {
   }
   
   /**
   Return ArrayList of all atrr names
   */
   public java.util.ArrayList arrayListOfAttrNames() 
   {
      java.util.ArrayList vec = new java.util.ArrayList();
      vec.add("name");
      vec.add("uri");
      vec.add("exampleValue");
      vec.add("factType");
      vec.add("mnemonic");
   	
      return vec;
   }

   // generic set and get methods
   public void set (String fieldName, Object value)
   {
      // name
      if ("name".equals(fieldName)){				
         setName((String) value);
      }      else      // uri
      if ("uri".equals(fieldName)){				
         setUri((String) value);
      }      else      // exampleValue
      if ("exampleValue".equals(fieldName)){				
         setExampleValue((String) value);
      }      else      // factType
      if ("factType".equals(fieldName)){				
         setFactType((String) value);
      }      else      // mnemonic
      if ("mnemonic".equals(fieldName)){				
         setMnemonic((String) value);
      }//( toMany false || toMany2 true || qualified $qualified || 
// internalQualified false ||  
// role.Qualifier $role.Qualifier || ordered false || sorted false)
 //2[! (  ( toMany || !toMany2) && !( toMany && toMany2)  && role.Qualifier  ) ]
//2.2[ !( qualified && !internalQualified ) ]
 else// serviceScreen
      if ("serviceScreen".equals(fieldName)){				
         setServiceScreen ((fast.common.client.BuildingBlock) value);
      }//( toMany false || toMany2 true || qualified $qualified || 
// internalQualified false ||  
// role.Qualifier $role.Qualifier || ordered false || sorted false)
 //2[! (  ( toMany || !toMany2) && !( toMany && toMany2)  && role.Qualifier  ) ]
//2.2[ !( qualified && !internalQualified ) ]
 else// serviceScreen2
      if ("serviceScreen2".equals(fieldName)){				
         setServiceScreen2 ((fast.common.client.BuildingBlock) value);
      }   }  

   public void add (String fieldName, Object value)
   {
      set (fieldName, value);
   }

   public Object get (String fieldName)
   {
      // name
      if ("name".equals(fieldName)){
         return (String) getName();
      }
      else      // uri
      if ("uri".equals(fieldName)){
         return (String) getUri();
      }
      else      // exampleValue
      if ("exampleValue".equals(fieldName)){
         return (String) getExampleValue();
      }
      else      // factType
      if ("factType".equals(fieldName)){
         return (String) getFactType();
      }
      else      // mnemonic
      if ("mnemonic".equals(fieldName)){
         return (String) getMnemonic();
      }
      else      if ("serviceScreen".equals(fieldName))
      {				
         return getServiceScreen();
      }
      else      if ("serviceScreen2".equals(fieldName))
      {				
         return getServiceScreen2();
      }
      return null;
   }

   public static final String PROPERTY_EXAMPLE_VALUE = "exampleValue";

   private String exampleValue;

   public void setExampleValue (String value)
   {
      if ( ! JavaSDM.stringEquals (this.exampleValue, value))
      {
         String oldValue = this.exampleValue;
         this.exampleValue = value;
         getPropertyChangeSupport().firePropertyChange(PROPERTY_EXAMPLE_VALUE, oldValue, value);
      }
   }

   public FactPort withExampleValue (String value)
   {
      setExampleValue (value);
      return this;
   }

   public String getExampleValue ()
   {
      return this.exampleValue;
   }

   public static final String PROPERTY_FACT_TYPE = "factType";

   private String factType;

   public void setFactType (String value)
   {
      if ( ! JavaSDM.stringEquals (this.factType, value))
      {
         String oldValue = this.factType;
         this.factType = value;
         getPropertyChangeSupport().firePropertyChange(PROPERTY_FACT_TYPE, oldValue, value);
      }
   }

   public FactPort withFactType (String value)
   {
      setFactType (value);
      return this;
   }

   public String getFactType ()
   {
      return this.factType;
   }

   public static final String PROPERTY_MNEMONIC = "mnemonic";

   private String mnemonic;

   public void setMnemonic (String value)
   {
      if ( ! JavaSDM.stringEquals (this.mnemonic, value))
      {
         String oldValue = this.mnemonic;
         this.mnemonic = value;
         getPropertyChangeSupport().firePropertyChange(PROPERTY_MNEMONIC, oldValue, value);
      }
   }

   public FactPort withMnemonic (String value)
   {
      setMnemonic (value);
      return this;
   }

   public String getMnemonic ()
   {
      return this.mnemonic;
   }

   public static final String PROPERTY_NAME = "name";

   private String name;

   public void setName (String value)
   {
      if ( ! JavaSDM.stringEquals (this.name, value))
      {
         String oldValue = this.name;
         this.name = value;
         getPropertyChangeSupport().firePropertyChange(PROPERTY_NAME, oldValue, value);
      }
   }

   public FactPort withName (String value)
   {
      setName (value);
      return this;
   }

   public String getName ()
   {
      return this.name;
   }

   /**
    * <pre>
    *           0..*     postconditions     0..1
    * FactPort ------------------------- BuildingBlock
    *           postconditions               serviceScreen2
    * </pre>
    */
   public static final String PROPERTY_SERVICE_SCREEN2 = "serviceScreen2";

   private BuildingBlock serviceScreen2;

   public boolean setServiceScreen2 (BuildingBlock value)
   {
      boolean changed = false;

      if (this.serviceScreen2 != value)
      {
      
         BuildingBlock oldValue = this.serviceScreen2;
         FactPort source = this;
         if (this.serviceScreen2 != null)
         {
            this.serviceScreen2 = null;
            oldValue.removeFromPostconditions (this);
         }
         this.serviceScreen2 = value;

         if (value != null)
         {
            value.addToPostconditions (this);
         }
            getPropertyChangeSupport().firePropertyChange(PROPERTY_SERVICE_SCREEN2, oldValue, value);
         changed = true;
      
      }
      return changed;
   }

   public FactPort withServiceScreen2 (BuildingBlock value)
   {
      setServiceScreen2 (value);
      return this;
   }

   public BuildingBlock getServiceScreen2 ()
   {
      return this.serviceScreen2;
   }

   /**
    * <pre>
    *           0..*     preconditions     0..1
    * FactPort ------------------------- BuildingBlock
    *           preconditions               serviceScreen
    * </pre>
    */
   public static final String PROPERTY_SERVICE_SCREEN = "serviceScreen";

   private BuildingBlock serviceScreen;

   public boolean setServiceScreen (BuildingBlock value)
   {
      boolean changed = false;

      if (this.serviceScreen != value)
      {
      
         BuildingBlock oldValue = this.serviceScreen;
         FactPort source = this;
         if (this.serviceScreen != null)
         {
            this.serviceScreen = null;
            oldValue.removeFromPreconditions (this);
         }
         this.serviceScreen = value;

         if (value != null)
         {
            value.addToPreconditions (this);
         }
            getPropertyChangeSupport().firePropertyChange(PROPERTY_SERVICE_SCREEN, oldValue, value);
         changed = true;
      
      }
      return changed;
   }

   public FactPort withServiceScreen (BuildingBlock value)
   {
      setServiceScreen (value);
      return this;
   }

   public BuildingBlock getServiceScreen ()
   {
      return this.serviceScreen;
   }

   public static final String PROPERTY_URI = "uri";

   private String uri;

   public void setUri (String value)
   {
      if ( ! JavaSDM.stringEquals (this.uri, value))
      {
         String oldValue = this.uri;
         this.uri = value;
         getPropertyChangeSupport().firePropertyChange(PROPERTY_URI, oldValue, value);
      }
   }

   public FactPort withUri (String value)
   {
      setUri (value);
      return this;
   }

   public String getUri ()
   {
      return this.uri;
   }

   public void removeYou()
   {
      this.setServiceScreen2 (null);
      this.setServiceScreen (null);
      super.removeYou ();
   }
}


