/*
 * GWT compliant generated by Fujaba - CodeGen2 version 03.12.2009
 */

package fast.common.client;

import fast.common.client.BuildingBlock;
import fujaba.web.runtime.client.CObject;
import fujaba.web.runtime.client.reflect.*;
import fujaba.web.runtime.client.*;
import java.util.*;
import com.google.gwt.event.dom.client.ClickHandler;
import com.google.gwt.event.dom.client.ClickEvent;




public class TemplateParameter extends CObject implements PropertyChangeClient
{

   public void removeAllFrom(String className) 
   {
   }
   
   /**
   Return ArrayList of all atrr names
   */
   public java.util.ArrayList arrayListOfAttrNames() 
   {
      java.util.ArrayList vec = new java.util.ArrayList();
      vec.add("name");
      vec.add("value");
   	
      return vec;
   }

   // generic set and get methods
   public void set (String fieldName, Object value)
   {
      // name
      if ("name".equals(fieldName)){
         setName((String) value);
      }      else      // value
      if ("value".equals(fieldName)){
         setValue((String) value);
      }  else// serviceScreen
      if ("serviceScreen".equals(fieldName)){
         setServiceScreen ((fast.common.client.BuildingBlock) value);
      }   }  

   public void add (String fieldName, Object value)
   {
      set (fieldName, value);
   }

   public Object get (String fieldName)
   {
      // name
      if ("name".equals(fieldName)){
         return (String) getName();
      }
      else      // value
      if ("value".equals(fieldName)){
         return (String) getValue();
      }
      else      if ("serviceScreen".equals(fieldName))
      {
         return getServiceScreen();
      }
      return null;
   }
	protected final PropertyChangeSupport listeners = new PropertyChangeSupport(this);

	public void addPropertyChangeListener(PropertyChangeListener listener)
	{
		getPropertyChangeSupport().addPropertyChangeListener(listener);
	}

	public void removePropertyChangeListener(PropertyChangeListener listener)
	{
		getPropertyChangeSupport().removePropertyChangeListener(listener);
	}

	public void addPropertyChangeListener(String property, PropertyChangeListener listener)
	{
		getPropertyChangeSupport().addPropertyChangeListener(property, listener);
	}

	public void removePropertyChangeListener(String property, PropertyChangeListener listener)
	{
		getPropertyChangeSupport().removePropertyChangeListener(property, listener);
	}

	public PropertyChangeSupport getPropertyChangeSupport()
	{
		return listeners;
	}


   public static final String PROPERTY_NAME = "name";

   private String name;

   public void setName (String value)
   {
      if ( ! JavaSDM.stringEquals (this.name, value))
      {
         String oldValue = this.name;
         this.name = value;
         getPropertyChangeSupport().firePropertyChange(PROPERTY_NAME, oldValue, value);
      }
   }

   public TemplateParameter withName (String value)
   {
      setName (value);
      return this;
   }

   public String getName ()
   {
      return this.name;
   }

   /**
    * <pre>
    *           0..n     templateParameters     0..1
    * TemplateParameter ------------------------- BuildingBlock
    *           templateParameters               serviceScreen
    * </pre>
    */

   private transient BuildingBlock serviceScreen;

   public boolean setServiceScreen (BuildingBlock value)
   {
      boolean changed = false;

      if (this.serviceScreen != value)
      {
      
         BuildingBlock oldValue = this.serviceScreen;
         TemplateParameter source = this;
         if (this.serviceScreen != null)
         {
            this.serviceScreen = null;
            oldValue.removeFromTemplateParameters (this);
         }
         this.serviceScreen = value;

         if (value != null)
         {
            value.addToTemplateParameters (this);
         }
         changed = true;
      
      }
      return changed;
   }

   public TemplateParameter withServiceScreen (BuildingBlock value)
   {
      setServiceScreen (value);
      return this;
   }

   public BuildingBlock getServiceScreen ()
   {
      return this.serviceScreen;
   }

   public static final String PROPERTY_VALUE = "value";

   private String value;

   public void setValue (String value)
   {
      if ( ! JavaSDM.stringEquals (this.value, value))
      {
         String oldValue = this.value;
         this.value = value;
         getPropertyChangeSupport().firePropertyChange(PROPERTY_VALUE, oldValue, value);
      }
   }

   public TemplateParameter withValue (String value)
   {
      setValue (value);
      return this;
   }

   public String getValue ()
   {
      return this.value;
   }

   public void removeYou()
   {
      this.setServiceScreen (null);
   }
}


